version: "2"
services:
  backend:
    container_name: template-backend
    build:
      context: backend
    image: template-backend:latest
    ports:
      - "8080:8080"
    restart: always
  frontend:
    container_name: template-frontend
    build:
      context: frontend
    image: template-frontend:latest
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend